# Generated by Django 2.1.15 on 2022-03-31 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_setting'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Setting',
            new_name='World',
        ),
    ]
